### ISSUE TITLE
Update selected/all extensions

### ISSUE THREAD

**Issue by jenskutilek** [robofont-mechanic/mechanic-2#4]
It would be great if the extension list would allow multiple selection, so you could select all and then hit the update button to update all installed extensions in one go.

**Comment by typemytype** [comment]
the issue is that multiple extension list items could have different states: they could be already installed or not, some need updates, they could be items from the extension store...

fe see the connection between a selection and button titles: https://github.com/robofont-mechanic/mechanic-2/blob/master/Mechanic2.roboFontExt/lib/mechanic2/ui/controller.py#L157-L172

mostly a ui problem and could be solved

**Comment by typemytype** [comment]
please reopen if this is still an issue :)
